version: "3"

services:
  springboot:
    build:
      context: ./bibleo-app
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"

  reactjs:
    build:
      context: ./bibleo-front
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - springboot
