# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the JAR file into the container
COPY ./src/main/java/com/isamm/bibleoapp/BibleoAppApplication.jar app.jar

# Expose port 8080
EXPOSE 8080

# Define the command to run your Spring Boot app
CMD ["java", "-jar", "app.jar"]